"""
Conduit Domain — Repository and service protocols.

Domain defines the interfaces. Infrastructure provides implementations.
This enforces the dependency rule: Domain never depends on Infrastructure.
"""

from typing import Protocol
from uuid import UUID

from conduit.domain.entities.integration import Integration
from conduit.domain.entities.pipeline import Pipeline, Revision
from conduit.domain.entities.run import Run, Step
from conduit.domain.entities.workspace import User, Workspace


# ── Repository Protocols ──


class UserRepository(Protocol):
    def find_by_id(self, user_id: UUID) -> User | None: ...
    def find_by_email(self, email: str) -> User | None: ...
    def save(self, user: User) -> User: ...


class WorkspaceRepository(Protocol):
    def find_by_id(self, workspace_id: UUID) -> Workspace | None: ...
    def find_by_slug(self, slug: str) -> Workspace | None: ...
    def list_for_user(self, user_id: UUID) -> list[Workspace]: ...
    def save(self, workspace: Workspace) -> Workspace: ...


class IntegrationRepository(Protocol):
    def find_by_id(self, integration_id: UUID) -> Integration | None: ...
    def list_by_workspace(self, workspace_id: UUID) -> list[Integration]: ...
    def save(self, integration: Integration) -> Integration: ...
    def soft_delete(self, integration_id: UUID) -> None: ...


class PipelineRepository(Protocol):
    def find_by_id(self, pipeline_id: UUID) -> Pipeline | None: ...
    def list_by_workspace(self, workspace_id: UUID) -> list[Pipeline]: ...
    def save(self, pipeline: Pipeline) -> Pipeline: ...
    def soft_delete(self, pipeline_id: UUID) -> None: ...


class RevisionRepository(Protocol):
    def find_by_id(self, revision_id: UUID) -> Revision | None: ...
    def list_by_pipeline(self, pipeline_id: UUID) -> list[Revision]: ...
    def save(self, revision: Revision) -> Revision: ...
    def next_number(self, pipeline_id: UUID) -> int: ...


class RunRepository(Protocol):
    def find_by_id(self, run_id: UUID) -> Run | None: ...
    def list_by_workspace(
        self, workspace_id: UUID, *, limit: int = 50, offset: int = 0
    ) -> list[Run]: ...
    def list_by_pipeline(self, pipeline_id: UUID) -> list[Run]: ...
    def save(self, run: Run) -> Run: ...


class StepRepository(Protocol):
    def list_by_run(self, run_id: UUID) -> list[Step]: ...
    def save(self, step: Step) -> Step: ...
    def save_many(self, steps: list[Step]) -> list[Step]: ...


# ── Event Bus Protocol ──


class EventBus(Protocol):
    def emit(self, event: object) -> None: ...
