"""Add config to Integration

Revision ID: 0934c3ad49ae
Revises: ed327d0cf6e9
Create Date: 2026-03-08 15:58:42.176521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0934c3ad49ae'
down_revision: Union[str, Sequence[str], None] = 'ed327d0cf6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_foreign_key('fk_pipelines_published_revision', 'pipelines', 'revisions', ['published_revision_id'], ['id'], use_alter=True)
    op.alter_column('stages', 'position_x',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('stages', 'position_y',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('users', sa.Column('auth_provider_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider_id')
    op.alter_column('stages', 'position_y',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('stages', 'position_x',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('fk_pipelines_published_revision', 'pipelines', type_='foreignkey')
    op.drop_column('integrations', 'config')
    # ### end Alembic commands ###
